### ISSUE TITLE
Fails to build with kwin 5.93.0

### ISSUE THREAD

**Issue by solopasha** [matinlotfali/KDE-Rounded-Corners#160]
logs:
```
/builddir/build/BUILD/KDE-Rounded-Corners-d76942a1055ac872c50d8d80479e9660de032497/src/ShapeCornersShader.cpp:100:42: error: ‘ModelViewProjectionMatri
x’ is not a member of ‘KWin::GLShader’
  100 |     m_shader->setUniform(KWin::GLShader::ModelViewProjectionMatrix, mvp);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by solopasha** [comment]
Opps, not kwin 5.93.0 but with commits from the Plasma/6.0 branch. Builds fine with: 
```
diff --git a/src/ShapeCornersShader.cpp b/src/ShapeCornersShader.cpp
index f7801c9..8044e80 100644
--- a/src/ShapeCornersShader.cpp
+++ b/src/ShapeCornersShader.cpp
@@ -97,7 +97,7 @@ ShapeCornersShader::Bind(KWin::EffectWindow *w, qreal scale) const {
 const std::unique_ptr<KWin::GLShader>&
 ShapeCornersShader::Bind(const QMatrix4x4& mvp, KWin::EffectWindow *w, qreal scale) const {
     Bind(w, scale);
-    m_shader->setUniform(KWin::GLShader::ModelViewProjectionMatrix, mvp);
+    m_shader->setUniform(KWin::GLShader::Mat4Uniform::ModelViewProjectionMatrix, mvp);
     return m_shader;
 }
 
```

**Comment by matinlotfali** [comment]
This should be fixed in #105
